main: protocol3.Main
name: protocol3
version: 1.0.0
api-version: 1.16
depend: [ ProtocolLib ]
author: d2k11
commands:
  kit:
   description: funny command
  mute:
   description: mute player
  dupehand:
   description: INTERNAL USE ONLY
  vm:
   description: vote mute
  msg:
   description: message
  r:
   description: reply
  tps:
   description: tps
  say:
   description: say
  discord:
   description: discord
  kill:
   description: kill
  setdonator:
   description: sd
  about:
   description: about
  vote:
   description: vote
  restart:
   description: restart
  sign:
   description: sign
  admin:
   description: admin
  stats:
   description: stats
  redeem:
   description: redeem
  lagfag:
   description: lagfag
  tjm:
   description: tjm
  server:
   description: server
  help:
   desription: help
